---
title: "Stats 209 Final - EDA"
author: "Andri, Eden, Veronica"
date: "11/8/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r warning=FALSE,message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
source('dataProcessing.R')
```

```{r}
dlexp = loadData()
```


```{r}
# start of with plots displaying Z and Y, not including X
del_cue_names <- c('0' = "No Video", '1' = "Video")
party_cue_names <- c('0' = "No Party Cue", '1' = "Party Cue")


ggplot(data=dlexp, aes(x=response)) + 
  geom_bar(color="black", fill="lightblue") + facet_grid(party.cues ~ video, labeller = labeller(
        party.cues = party_cue_names,
        video = del_cue_names
    ))

```

```{r}
party_names = c('1' = "Democrat", '2' = "Independent", '3' = "Republican") # not dict, fix later maybe
party_cols = c('lightblue', 'lightgreen', 'lightcoral')

party_hist = function(pid){
  data = filter(dlexp, pid3 == pid)
  ggplot(data=data, aes(x=response)) + 
  geom_bar(color="black", fill=party_cols[pid]) + facet_grid(party.cues ~ video, labeller = labeller(
        party.cues = party_cue_names,
        video = del_cue_names
    )) + ggtitle(party_names[pid])
  
}

party_hist(1)
party_hist(2)
party_hist(3)
```



```{r}
del_cue_names = c('0' = "No Video", '1' = "Video")
female_names = c('0' = "Male", '1' = "Female")
white_names = c('0' = "Non-White", '1' = "White")

hist_factor = function(binary_var, var_names){
  ggplot(data=dlexp, aes(x=response)) + 
  geom_bar(color="black", fill="lightblue") + facet_grid(rows = vars(.data[[binary_var]]), cols = vars(video),
                                                         labeller = labeller( .rows = as_labeller(var_names), .cols = as_labeller(del_cue_names)))
  
}

hist_factor("female", female_names)
hist_factor("white", white_names)
```

```{r warning=FALSE,message=FALSE}
# include this plot

dat = dlexp %>% 
   filter(party.cues == 1) %>%
   group_by(across(all_of(c("pid3", "Z", "Y")))) %>%
   summarize(Frequency = n())

dat$Z = as.factor(dat$Z)


party_bar = function(pid){
  dat_ = filter(dat, pid3 == pid)
  ggplot(data=dat_, aes(x=Y, y=Frequency, fill=Z)) +
    geom_bar(stat="identity",  position="dodge", colour = "black") + ggtitle(party_names[pid])
  
}


party_bar(1)
party_bar(2)
party_bar(3)
```


```{r warning=FALSE,message=FALSE}
datInc = dlexp %>% 
   filter(party.cues == 1) %>%
   group_by(across(all_of(c("pid3", "incomeQuant", "Z", "Y")))) %>%
   summarize(Frequency = n())

datInc$Z = as.factor(datInc$Z)

income_plot = function(pid){
  dat = filter(datInc, pid3 == pid)
  ggplot(data=dat, aes(x=Y, y=Frequency, fill=Z)) + 
    geom_bar(stat="identity",  position="dodge", colour = "black") + facet_wrap(~incomeQuant, scales = "free") + ggtitle(party_names[pid])
  
}

income_plot(1)
income_plot(2)
income_plot(3)
```

```{r warning=FALSE,message=FALSE}
datEduc = dlexp %>% 
   filter(party.cues == 1) %>%
   group_by(across(all_of(c("pid3", "educationLevel", "Z", "Y")))) %>%
   summarize(Frequency = n())

datEduc$Z = as.factor(datEduc$Z)

educ_plot = function(pid){
  dat = filter(datEduc, pid3 == pid)
  
  # maintain order of education - high school, college, ....
  dat = transform(dat,
      educationLevel=factor(educationLevel,levels=c("High School","Some College Experience","4-Year College Degree", "Graduate Degree")))

  ggplot(data = dat,
      aes(x=Y, y=Frequency, fill=Z)) + geom_bar(stat="identity",  position="dodge", colour = "black") +
    facet_wrap(~educationLevel, scales = "free") +
    ggtitle(party_names[pid])
    
  
}

educ_plot(1)
educ_plot(2)
educ_plot(3)
```

```{r}
# Education-Income Correlation

dat = transform(dlexp,
      educationLevel=factor(educationLevel,levels=c("High School","Some College Experience","4-Year College Degree", "Graduate Degree")))
ggplot(aes(y = income, x = educationLevel), data = dat) + 
geom_boxplot(aes(fill=educationLevel)) + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

```



```{r}
dlexp %>% 
   group_by(across(all_of(c("video","party.cues")))) %>% 
   summarize(mean_response = mean(response), cnt = n())
```


```{r}
dlexp %>% 
   group_by(across(all_of(c("age_bucket", "video")))) %>% 
   summarize(mean_response=mean(response), cnt = n())
```

See how video does not affect opinion of age group 40-49 as much as others. This is not surprising ...

```{r}
dd = dlexp %>% 
   group_by(across(all_of(c("income_bucket", "video", "pol_party")))) %>% 
   summarize(mean_response=mean(response), cnt = n())
```

```{r}
dlexp %>% 
   group_by(across(all_of(c("educ4", "video")))) %>% 
   summarize(mean_response=mean(response), cnt = n())
```

Again, notice how video does not seem to effect the "middleground" group as much as others.

